# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgreementAllTP.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgreementAllTP(object):
    def setupUi(self, AgreementAllTP):
        AgreementAllTP.setObjectName("AgreementAllTP")
        AgreementAllTP.resize(800, 600)
        AgreementAllTP.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(AgreementAllTP)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetALLTP = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetALLTP.sizePolicy().hasHeightForWidth())
        self.tableWidgetALLTP.setSizePolicy(sizePolicy)
        self.tableWidgetALLTP.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetALLTP.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetALLTP.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetALLTP.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetALLTP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetALLTP.setStyleSheet("background:rgb(243, 255, 234);")
        self.tableWidgetALLTP.setObjectName("tableWidgetALLTP")
        self.tableWidgetALLTP.setColumnCount(1)
        self.tableWidgetALLTP.setRowCount(0)
        self.tableWidgetALLTP.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetALLTP.setHorizontalHeaderItem(0, item)
        self.gridLayout.addWidget(self.tableWidgetALLTP, 0, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 1, 0, 1, 1)
        AgreementAllTP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AgreementAllTP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        AgreementAllTP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AgreementAllTP)
        self.statusbar.setObjectName("statusbar")
        AgreementAllTP.setStatusBar(self.statusbar)

        self.retranslateUi(AgreementAllTP)
        QtCore.QMetaObject.connectSlotsByName(AgreementAllTP)

    def retranslateUi(self, AgreementAllTP):
        _translate = QtCore.QCoreApplication.translate
        AgreementAllTP.setWindowTitle(_translate("AgreementAllTP", "MainWindow"))
        self.tableWidgetALLTP.setWhatsThis(_translate("AgreementAllTP", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetALLTP.horizontalHeaderItem(0)
        item.setText(_translate("AgreementAllTP", "Наименование ТП"))
        self.pushButtonBack.setText(_translate("AgreementAllTP", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgreementAllTP = QtWidgets.QMainWindow()
    ui = Ui_AgreementAllTP()
    ui.setupUi(AgreementAllTP)
    AgreementAllTP.show()
    sys.exit(app.exec_())
