# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgreementCardNewAgreement.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgreementUserCard(object):
    def setupUi(self, AgreementUserCard):
        AgreementUserCard.setObjectName("AgreementUserCard")
        AgreementUserCard.resize(958, 603)
        AgreementUserCard.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(AgreementUserCard)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 50))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_3.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEditPathToDownload = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPathToDownload.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditPathToDownload.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditPathToDownload.setObjectName("lineEditPathToDownload")
        self.gridLayout.addWidget(self.lineEditPathToDownload, 0, 1, 1, 1)
        self.pushButtonCheckOldAgreement_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckOldAgreement_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCheckOldAgreement_3.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCheckOldAgreement_3.setObjectName("pushButtonCheckOldAgreement_3")
        self.gridLayout.addWidget(self.pushButtonCheckOldAgreement_3, 1, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 2)
        self.scrollAreaGosts = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaGosts.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollAreaGosts.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.scrollAreaGosts.setWidgetResizable(True)
        self.scrollAreaGosts.setObjectName("scrollAreaGosts")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 551, 372))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollAreaGosts.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.addWidget(self.scrollAreaGosts, 1, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 50))
        self.label_8.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setMinimumSize(QtCore.QSize(0, 50))
        self.labelName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelName.setObjectName("labelName")
        self.gridLayout_3.addWidget(self.labelName, 0, 1, 1, 1)
        self.labelNewName = QtWidgets.QLabel(self.centralwidget)
        self.labelNewName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelNewName.setObjectName("labelNewName")
        self.gridLayout_3.addWidget(self.labelNewName, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.labelUserComment = QtWidgets.QLabel(self.centralwidget)
        self.labelUserComment.setMinimumSize(QtCore.QSize(200, 50))
        self.labelUserComment.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelUserComment.setObjectName("labelUserComment")
        self.gridLayout_3.addWidget(self.labelUserComment, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_2.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 2, 1)
        AgreementUserCard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AgreementUserCard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 21))
        self.menubar.setObjectName("menubar")
        AgreementUserCard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AgreementUserCard)
        self.statusbar.setObjectName("statusbar")
        AgreementUserCard.setStatusBar(self.statusbar)

        self.retranslateUi(AgreementUserCard)
        QtCore.QMetaObject.connectSlotsByName(AgreementUserCard)

    def retranslateUi(self, AgreementUserCard):
        _translate = QtCore.QCoreApplication.translate
        AgreementUserCard.setWindowTitle(_translate("AgreementUserCard", "MainWindow"))
        self.label_3.setText(_translate("AgreementUserCard", "ГОСТ В ТП"))
        self.label_4.setText(_translate("AgreementUserCard", "Путь для выгрузки"))
        self.pushButtonCheckOldAgreement_3.setText(_translate("AgreementUserCard", "Загрузить"))
        self.pushButtonBack.setText(_translate("AgreementUserCard", "Назад"))
        self.label.setText(_translate("AgreementUserCard", "Наименование"))
        self.label_8.setText(_translate("AgreementUserCard", "Новое наименование"))
        self.labelName.setText(_translate("AgreementUserCard", "текст"))
        self.labelNewName.setText(_translate("AgreementUserCard", "текст"))
        self.labelUserComment.setText(_translate("AgreementUserCard", "текст"))
        self.label_2.setText(_translate("AgreementUserCard", "Комментарий "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgreementUserCard = QtWidgets.QMainWindow()
    ui = Ui_AgreementUserCard()
    ui.setupUi(AgreementUserCard)
    AgreementUserCard.show()
    sys.exit(app.exec_())
