# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgreementCardBadAgreeement.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgreementUserCardBadAgreement(object):
    def setupUi(self, AgreementUserCardBadAgreement):
        AgreementUserCardBadAgreement.setObjectName("AgreementUserCardBadAgreement")
        AgreementUserCardBadAgreement.resize(958, 603)
        AgreementUserCardBadAgreement.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(AgreementUserCardBadAgreement)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonCheckOldAgreement_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckOldAgreement_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCheckOldAgreement_3.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCheckOldAgreement_3.setObjectName("pushButtonCheckOldAgreement_3")
        self.gridLayout.addWidget(self.pushButtonCheckOldAgreement_3, 6, 4, 1, 1)
        self.labelNewName = QtWidgets.QLabel(self.centralwidget)
        self.labelNewName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelNewName.setObjectName("labelNewName")
        self.gridLayout.addWidget(self.labelNewName, 1, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 50))
        self.label_8.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.labelUserComment = QtWidgets.QLabel(self.centralwidget)
        self.labelUserComment.setMinimumSize(QtCore.QSize(200, 50))
        self.labelUserComment.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelUserComment.setObjectName("labelUserComment")
        self.gridLayout.addWidget(self.labelUserComment, 2, 1, 1, 2)
        self.lineEditPathToDownload_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPathToDownload_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditPathToDownload_2.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditPathToDownload_2.setObjectName("lineEditPathToDownload_2")
        self.gridLayout.addWidget(self.lineEditPathToDownload_2, 4, 1, 1, 5)
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setMinimumSize(QtCore.QSize(0, 50))
        self.labelName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_2.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEditPathToDownload = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPathToDownload.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditPathToDownload.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditPathToDownload.setObjectName("lineEditPathToDownload")
        self.gridLayout.addWidget(self.lineEditPathToDownload, 5, 1, 1, 5)
        self.pushButtonCheckOldAgreement_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckOldAgreement_4.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCheckOldAgreement_4.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCheckOldAgreement_4.setObjectName("pushButtonCheckOldAgreement_4")
        self.gridLayout.addWidget(self.pushButtonCheckOldAgreement_4, 6, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 50))
        self.label_5.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 6, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButtonToAgreemennt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonToAgreemennt.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonToAgreemennt.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonToAgreemennt.setObjectName("pushButtonToAgreemennt")
        self.gridLayout.addWidget(self.pushButtonToAgreemennt, 6, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.scrollAreaGosts = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaGosts.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollAreaGosts.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.scrollAreaGosts.setWidgetResizable(True)
        self.scrollAreaGosts.setObjectName("scrollAreaGosts")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 413, 374))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollAreaGosts.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollAreaGosts, 0, 3, 4, 3)
        AgreementUserCardBadAgreement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AgreementUserCardBadAgreement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 21))
        self.menubar.setObjectName("menubar")
        AgreementUserCardBadAgreement.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AgreementUserCardBadAgreement)
        self.statusbar.setObjectName("statusbar")
        AgreementUserCardBadAgreement.setStatusBar(self.statusbar)

        self.retranslateUi(AgreementUserCardBadAgreement)
        QtCore.QMetaObject.connectSlotsByName(AgreementUserCardBadAgreement)

    def retranslateUi(self, AgreementUserCardBadAgreement):
        _translate = QtCore.QCoreApplication.translate
        AgreementUserCardBadAgreement.setWindowTitle(_translate("AgreementUserCardBadAgreement", "MainWindow"))
        self.pushButtonCheckOldAgreement_3.setText(_translate("AgreementUserCardBadAgreement", "Загрузить"))
        self.labelNewName.setText(_translate("AgreementUserCardBadAgreement", "текст"))
        self.label_8.setText(_translate("AgreementUserCardBadAgreement", "Новое наименование"))
        self.labelUserComment.setText(_translate("AgreementUserCardBadAgreement", "текст"))
        self.labelName.setText(_translate("AgreementUserCardBadAgreement", "текст"))
        self.label_2.setText(_translate("AgreementUserCardBadAgreement", "Комментарий администратора"))
        self.pushButtonCheckOldAgreement_4.setText(_translate("AgreementUserCardBadAgreement", "Выбрать новый файл"))
        self.label_4.setText(_translate("AgreementUserCardBadAgreement", "Путь для выгрузки"))
        self.label_5.setText(_translate("AgreementUserCardBadAgreement", "Путь до файла"))
        self.pushButtonBack.setText(_translate("AgreementUserCardBadAgreement", "Назад"))
        self.label.setText(_translate("AgreementUserCardBadAgreement", "Наименование"))
        self.pushButtonToAgreemennt.setText(_translate("AgreementUserCardBadAgreement", "Отправить на согласование"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgreementUserCardBadAgreement = QtWidgets.QMainWindow()
    ui = Ui_AgreementUserCardBadAgreement()
    ui.setupUi(AgreementUserCardBadAgreement)
    AgreementUserCardBadAgreement.show()
    sys.exit(app.exec_())
