# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AllAgreement.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllAgreementUser(object):
    def setupUi(self, AllAgreementUser):
        AllAgreementUser.setObjectName("AllAgreementUser")
        AllAgreementUser.resize(1004, 683)
        AllAgreementUser.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(AllAgreementUser)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.pushButtonCheckOldAgreement = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckOldAgreement.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCheckOldAgreement.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCheckOldAgreement.setObjectName("pushButtonCheckOldAgreement")
        self.gridLayout.addWidget(self.pushButtonCheckOldAgreement, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_2.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.pushButtonCreateNewAgreement = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCreateNewAgreement.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCreateNewAgreement.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCreateNewAgreement.setObjectName("pushButtonCreateNewAgreement")
        self.gridLayout.addWidget(self.pushButtonCreateNewAgreement, 2, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 2, 3, 1, 1)
        self.tableWidgetAllAgreement = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetAllAgreement.sizePolicy().hasHeightForWidth())
        self.tableWidgetAllAgreement.setSizePolicy(sizePolicy)
        self.tableWidgetAllAgreement.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetAllAgreement.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetAllAgreement.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetAllAgreement.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetAllAgreement.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetAllAgreement.setStyleSheet("background:rgb(243, 255, 234);")
        self.tableWidgetAllAgreement.setObjectName("tableWidgetAllAgreement")
        self.tableWidgetAllAgreement.setColumnCount(3)
        self.tableWidgetAllAgreement.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        self.tableWidgetAllAgreement.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch) # 2
        self.tableWidgetAllAgreement.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch) # 2
        self.tableWidgetAllAgreement.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidgetAllAgreement, 1, 0, 1, 2)
        self.tableWidgetAllAgreement_2 = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetAllAgreement_2.sizePolicy().hasHeightForWidth())
        self.tableWidgetAllAgreement_2.setSizePolicy(sizePolicy)
        self.tableWidgetAllAgreement_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetAllAgreement_2.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetAllAgreement_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetAllAgreement_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetAllAgreement_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetAllAgreement_2.setStyleSheet("background:rgb(243, 255, 234);")
        self.tableWidgetAllAgreement_2.setObjectName("tableWidgetAllAgreement_2")
        self.tableWidgetAllAgreement_2.setColumnCount(3)
        self.tableWidgetAllAgreement_2.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        self.tableWidgetAllAgreement_2.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch) # 2
        self.tableWidgetAllAgreement_2.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch) # 2
        self.tableWidgetAllAgreement_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement_2.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidgetAllAgreement_2, 1, 2, 1, 2)
        AllAgreementUser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AllAgreementUser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 21))
        self.menubar.setObjectName("menubar")
        AllAgreementUser.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AllAgreementUser)
        self.statusbar.setObjectName("statusbar")
        AllAgreementUser.setStatusBar(self.statusbar)

        self.retranslateUi(AllAgreementUser)
        QtCore.QMetaObject.connectSlotsByName(AllAgreementUser)

    def retranslateUi(self, AllAgreementUser):
        _translate = QtCore.QCoreApplication.translate
        AllAgreementUser.setWindowTitle(_translate("AllAgreementUser", "MainWindow"))
        self.label.setText(_translate("AllAgreementUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">На рассмотрении</span></p></body></html>"))
        self.pushButtonCheckOldAgreement.setText(_translate("AllAgreementUser", "Просмотр старых согласований"))
        self.label_2.setText(_translate("AllAgreementUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Требуется корректировка</span></p></body></html>"))
        self.pushButtonCreateNewAgreement.setText(_translate("AllAgreementUser", "Создать новую заявку"))
        self.pushButtonBack.setText(_translate("AllAgreementUser", "Назад"))
        self.tableWidgetAllAgreement.setWhatsThis(_translate("AllAgreementUser", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetAllAgreement.horizontalHeaderItem(0)
        item.setText(_translate("AllAgreementUser", "Наименование ТП"))
        item = self.tableWidgetAllAgreement.horizontalHeaderItem(1)
        item.setText(_translate("AllAgreementUser", "Дата создания"))
        item = self.tableWidgetAllAgreement.horizontalHeaderItem(2)
        item.setText(_translate("AllAgreementUser", "Комментарий"))
        self.tableWidgetAllAgreement_2.setWhatsThis(_translate("AllAgreementUser", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetAllAgreement_2.horizontalHeaderItem(0)
        item.setText(_translate("AllAgreementUser", "Наименование"))
        item = self.tableWidgetAllAgreement_2.horizontalHeaderItem(1)
        item.setText(_translate("AllAgreementUser", "Дата создания"))
        item = self.tableWidgetAllAgreement_2.horizontalHeaderItem(2)
        item.setText(_translate("AllAgreementUser", "Комментарий администратора"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AllAgreementUser = QtWidgets.QMainWindow()
    ui = Ui_AllAgreementUser()
    ui.setupUi(AllAgreementUser)
    AllAgreementUser.show()
    sys.exit(app.exec_())
