# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AllGosts.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllGosts(object):
    def setupUi(self, AllGosts):
        AllGosts.setObjectName("AllGosts")
        AllGosts.resize(1149, 710)
        AllGosts.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(AllGosts)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditPathDownload = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPathDownload.setMinimumSize(QtCore.QSize(700, 70))
        self.lineEditPathDownload.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.lineEditPathDownload.setObjectName("lineEditPathDownload")
        self.gridLayout.addWidget(self.lineEditPathDownload, 1, 1, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(286, 80))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 2, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(200, 70))
        self.label_4.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.tableWidgetAcrualTP = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetAcrualTP.sizePolicy().hasHeightForWidth())
        self.tableWidgetAcrualTP.setSizePolicy(sizePolicy)
        self.tableWidgetAcrualTP.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetAcrualTP.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetAcrualTP.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetAcrualTP.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetAcrualTP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetAcrualTP.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.tableWidgetAcrualTP.setObjectName("tableWidgetAcrualTP")
        self.tableWidgetAcrualTP.setColumnCount(3)
        self.tableWidgetAcrualTP.setRowCount(0)
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch) # 2
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch) # 2
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidgetAcrualTP, 0, 0, 1, 2)
        AllGosts.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AllGosts)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1149, 21))
        self.menubar.setObjectName("menubar")
        AllGosts.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AllGosts)
        self.statusbar.setObjectName("statusbar")
        AllGosts.setStatusBar(self.statusbar)

        self.retranslateUi(AllGosts)
        QtCore.QMetaObject.connectSlotsByName(AllGosts)

    def retranslateUi(self, AllGosts):
        _translate = QtCore.QCoreApplication.translate
        AllGosts.setWindowTitle(_translate("AllGosts", "MainWindow"))
        self.pushButtonBack.setText(_translate("AllGosts", "Назад"))
        self.label_4.setText(_translate("AllGosts", "Путь для выгрузки"))
        self.tableWidgetAcrualTP.setWhatsThis(_translate("AllGosts", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(0)
        item.setText(_translate("AllGosts", "Наименование"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(1)
        item.setText(_translate("AllGosts", "Дата изменения"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(2)
        item.setText(_translate("AllGosts", "Дата создания"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AllGosts = QtWidgets.QMainWindow()
    ui = Ui_AllGosts()
    ui.setupUi(AllGosts)
    AllGosts.show()
    sys.exit(app.exec_())
