# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AllTP.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ALLTPS(object):
    def setupUi(self, ALLTPS):
        ALLTPS.setObjectName("ALLTPS")
        ALLTPS.resize(723, 597)
        ALLTPS.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(ALLTPS)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("background:rgb(243, 255, 234);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("background:rgb(243, 255, 234);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidgetAcrualTP = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetAcrualTP.sizePolicy().hasHeightForWidth())
        self.tableWidgetAcrualTP.setSizePolicy(sizePolicy)
        self.tableWidgetAcrualTP.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetAcrualTP.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetAcrualTP.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetAcrualTP.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetAcrualTP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetAcrualTP.setStyleSheet("background:rgb(243, 255, 234);")
        self.tableWidgetAcrualTP.setObjectName("tableWidgetAcrualTP")
        self.tableWidgetAcrualTP.setColumnCount(2)
        self.tableWidgetAcrualTP.setRowCount(0)
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch) # 2
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.tableWidgetAcrualTP)
        self.tableWidgetOldTP = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetOldTP.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetOldTP.setStyleSheet("background:rgb(243, 255, 234);")
        self.tableWidgetOldTP.setObjectName("tableWidgetOldTP")
        self.tableWidgetOldTP.setColumnCount(2)
        self.tableWidgetOldTP.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOldTP.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOldTP.setHorizontalHeaderItem(1, item)
        self.tableWidgetOldTP.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        self.tableWidgetOldTP.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch) # 2
        self.horizontalLayout_2.addWidget(self.tableWidgetOldTP)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 2, 0, 1, 1)
        ALLTPS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ALLTPS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 21))
        self.menubar.setObjectName("menubar")
        ALLTPS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ALLTPS)
        self.statusbar.setObjectName("statusbar")
        ALLTPS.setStatusBar(self.statusbar)

        self.retranslateUi(ALLTPS)
        QtCore.QMetaObject.connectSlotsByName(ALLTPS)

    def retranslateUi(self, ALLTPS):
        _translate = QtCore.QCoreApplication.translate
        ALLTPS.setWindowTitle(_translate("ALLTPS", "MainWindow"))
        self.label.setText(_translate("ALLTPS", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Актуальные ТП</span></p></body></html>"))
        self.label_2.setText(_translate("ALLTPS", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Старые ТП</span></p></body></html>"))
        self.tableWidgetAcrualTP.setWhatsThis(_translate("ALLTPS", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(0)
        item.setText(_translate("ALLTPS", "Наименование"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(1)
        item.setText(_translate("ALLTPS", "Дата изменения"))
        self.tableWidgetOldTP.setWhatsThis(_translate("ALLTPS", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetOldTP.horizontalHeaderItem(0)
        item.setText(_translate("ALLTPS", "Наименование"))
        item = self.tableWidgetOldTP.horizontalHeaderItem(1)
        item.setText(_translate("ALLTPS", "Дата изменения"))
        self.pushButtonBack.setText(_translate("ALLTPS", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ALLTPS = QtWidgets.QMainWindow()
    ui = Ui_ALLTPS()
    ui.setupUi(ALLTPS)
    ALLTPS.show()
    sys.exit(app.exec_())
