# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateAgreement.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateAgreement(object):
    def setupUi(self, CreateAgreement):
        CreateAgreement.setObjectName("CreateAgreement")
        CreateAgreement.resize(1005, 684)
        CreateAgreement.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(CreateAgreement)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 50))
        self.label_8.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setMinimumSize(QtCore.QSize(0, 50))
        self.labelName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelName.setObjectName("labelName")
        self.gridLayout_2.addWidget(self.labelName, 0, 1, 1, 1)
        self.lineEditNewName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNewName.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditNewName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditNewName.setObjectName("lineEditNewName")
        self.gridLayout_2.addWidget(self.lineEditNewName, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_2.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEditComment = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditComment.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditComment.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditComment.setObjectName("lineEditComment")
        self.gridLayout_2.addWidget(self.lineEditComment, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        self.label_3.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.scrollAreaGosts = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaGosts.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollAreaGosts.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.scrollAreaGosts.setWidgetResizable(True)
        self.scrollAreaGosts.setObjectName("scrollAreaGosts")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 488, 395))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollAreaGosts.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.scrollAreaGosts, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(280, 50))
        self.label_4.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEditPathToDownload = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPathToDownload.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditPathToDownload.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditPathToDownload.setObjectName("lineEditPathToDownload")
        self.gridLayout.addWidget(self.lineEditPathToDownload, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(280, 50))
        self.label_5.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEditPathToCurrentVersion = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPathToCurrentVersion.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditPathToCurrentVersion.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditPathToCurrentVersion.setObjectName("lineEditPathToCurrentVersion")
        self.gridLayout.addWidget(self.lineEditPathToCurrentVersion, 1, 1, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonToAgreemennt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonToAgreemennt.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonToAgreemennt.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonToAgreemennt.setObjectName("pushButtonToAgreemennt")
        self.horizontalLayout.addWidget(self.pushButtonToAgreemennt)
        self.pushButtonDownload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDownload.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonDownload.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.horizontalLayout.addWidget(self.pushButtonDownload)
        self.pushButtonCheckOldAgreement_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckOldAgreement_4.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCheckOldAgreement_4.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCheckOldAgreement_4.setObjectName("pushButtonCheckOldAgreement_4")
        self.horizontalLayout.addWidget(self.pushButtonCheckOldAgreement_4)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout.addWidget(self.pushButtonBack)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        CreateAgreement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateAgreement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 21))
        self.menubar.setObjectName("menubar")
        CreateAgreement.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateAgreement)
        self.statusbar.setObjectName("statusbar")
        CreateAgreement.setStatusBar(self.statusbar)

        self.retranslateUi(CreateAgreement)
        QtCore.QMetaObject.connectSlotsByName(CreateAgreement)

    def retranslateUi(self, CreateAgreement):
        _translate = QtCore.QCoreApplication.translate
        CreateAgreement.setWindowTitle(_translate("CreateAgreement", "MainWindow"))
        self.label.setText(_translate("CreateAgreement", "Наименование"))
        self.label_8.setText(_translate("CreateAgreement", "Новое наименование"))
        self.labelName.setText(_translate("CreateAgreement", "текст"))
        self.label_2.setText(_translate("CreateAgreement", "Комментарий"))
        self.label_3.setText(_translate("CreateAgreement", "Выберите ГОСТ для ТП"))
        self.label_4.setText(_translate("CreateAgreement", "Путь для выгрузки"))
        self.label_5.setText(_translate("CreateAgreement", "Путь для загрузки текущей версии"))
        self.pushButtonToAgreemennt.setText(_translate("CreateAgreement", "Отправить на согласование"))
        self.pushButtonDownload.setText(_translate("CreateAgreement", "Загрузить"))
        self.pushButtonCheckOldAgreement_4.setText(_translate("CreateAgreement", "Выбрать файл"))
        self.pushButtonBack.setText(_translate("CreateAgreement", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateAgreement = QtWidgets.QMainWindow()
    ui = Ui_CreateAgreement()
    ui.setupUi(CreateAgreement)
    CreateAgreement.show()
    sys.exit(app.exec_())
