# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NeedChange.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NeedChange(object):
    def setupUi(self, NeedChange):
        NeedChange.setObjectName("NeedChange")
        NeedChange.resize(1138, 769)
        NeedChange.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(NeedChange)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetNeedChange = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetNeedChange.sizePolicy().hasHeightForWidth())
        self.tableWidgetNeedChange.setSizePolicy(sizePolicy)
        self.tableWidgetNeedChange.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetNeedChange.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetNeedChange.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetNeedChange.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetNeedChange.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetNeedChange.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.tableWidgetNeedChange.setObjectName("tableWidgetNeedChange")
        self.tableWidgetNeedChange.setColumnCount(2)
        self.tableWidgetNeedChange.setRowCount(0)
        self.tableWidgetNeedChange.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        self.tableWidgetNeedChange.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch) # 2
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidgetNeedChange.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidgetNeedChange.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidgetNeedChange, 0, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(286, 80))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 1, 0, 1, 1)
        NeedChange.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NeedChange)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 21))
        self.menubar.setObjectName("menubar")
        NeedChange.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NeedChange)
        self.statusbar.setObjectName("statusbar")
        NeedChange.setStatusBar(self.statusbar)

        self.retranslateUi(NeedChange)
        QtCore.QMetaObject.connectSlotsByName(NeedChange)

    def retranslateUi(self, NeedChange):
        _translate = QtCore.QCoreApplication.translate
        NeedChange.setWindowTitle(_translate("NeedChange", "MainWindow"))
        self.tableWidgetNeedChange.setWhatsThis(_translate("NeedChange", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetNeedChange.horizontalHeaderItem(0)
        item.setText(_translate("NeedChange", "Наименование"))
        item = self.tableWidgetNeedChange.horizontalHeaderItem(1)
        item.setText(_translate("NeedChange", "Требование изменений"))
        self.pushButtonBack.setText(_translate("NeedChange", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NeedChange = QtWidgets.QMainWindow()
    ui = Ui_NeedChange()
    ui.setupUi(NeedChange)
    NeedChange.show()
    sys.exit(app.exec_())
