# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OldAgreement.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OldAgreement(object):
    def setupUi(self, OldAgreement):
        OldAgreement.setObjectName("OldAgreement")
        OldAgreement.resize(800, 600)
        OldAgreement.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(OldAgreement)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 2, 0, 1, 1)
        self.tableWidgetAllAgreement = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetAllAgreement.sizePolicy().hasHeightForWidth())
        self.tableWidgetAllAgreement.setSizePolicy(sizePolicy)
        self.tableWidgetAllAgreement.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetAllAgreement.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetAllAgreement.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetAllAgreement.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetAllAgreement.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetAllAgreement.setStyleSheet("background:rgb(243, 255, 234);")
        self.tableWidgetAllAgreement.setObjectName("tableWidgetAllAgreement")
        self.tableWidgetAllAgreement.setColumnCount(4)
        self.tableWidgetAllAgreement.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        self.tableWidgetAllAgreement.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch) # 2
        self.tableWidgetAllAgreement.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch) # 1
        self.tableWidgetAllAgreement.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.Stretch) # 2
        self.tableWidgetAllAgreement.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAllAgreement.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidgetAllAgreement, 1, 0, 1, 1)
        OldAgreement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OldAgreement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        OldAgreement.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OldAgreement)
        self.statusbar.setObjectName("statusbar")
        OldAgreement.setStatusBar(self.statusbar)

        self.retranslateUi(OldAgreement)
        QtCore.QMetaObject.connectSlotsByName(OldAgreement)

    def retranslateUi(self, OldAgreement):
        _translate = QtCore.QCoreApplication.translate
        OldAgreement.setWindowTitle(_translate("OldAgreement", "MainWindow"))
        self.pushButtonBack.setText(_translate("OldAgreement", "Назад"))
        self.tableWidgetAllAgreement.setWhatsThis(_translate("OldAgreement", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetAllAgreement.horizontalHeaderItem(0)
        item.setText(_translate("OldAgreement", "Наименование"))
        item = self.tableWidgetAllAgreement.horizontalHeaderItem(1)
        item.setText(_translate("OldAgreement", "Комментарий пользователя"))
        item = self.tableWidgetAllAgreement.horizontalHeaderItem(2)
        item.setText(_translate("OldAgreement", "Комментарий администратора"))
        item = self.tableWidgetAllAgreement.horizontalHeaderItem(3)
        item.setText(_translate("OldAgreement", "Причина изменения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OldAgreement = QtWidgets.QMainWindow()
    ui = Ui_OldAgreement()
    ui.setupUi(OldAgreement)
    OldAgreement.show()
    sys.exit(app.exec_())
