# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OldTpCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1341, 494)
        MainWindow.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setStyleSheet("background:rgb(243, 255, 234);")
        self.label_name.setObjectName("label_name")
        self.horizontalLayout.addWidget(self.label_name)
        self.lineEditPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPath.setStyleSheet("background:rgb(243, 255, 234);")
        self.lineEditPath.setObjectName("lineEditPath")
        self.horizontalLayout.addWidget(self.lineEditPath)
        self.pushButtonDownload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDownload.setMinimumSize(QtCore.QSize(150, 20))
        self.pushButtonDownload.setStyleSheet("background:rgb(243, 255, 234);")
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.horizontalLayout.addWidget(self.pushButtonDownload)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout_2.addWidget(self.pushButtonBack, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelCreationDate_Name = QtWidgets.QLabel(self.centralwidget)
        self.labelCreationDate_Name.setMinimumSize(QtCore.QSize(0, 100))
        self.labelCreationDate_Name.setStyleSheet("background:rgb(243, 255, 234);")
        self.labelCreationDate_Name.setObjectName("labelCreationDate_Name")
        self.gridLayout.addWidget(self.labelCreationDate_Name, 0, 0, 1, 1)
        self.labelCreationDate_Name_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelCreationDate_Name_2.setMinimumSize(QtCore.QSize(0, 100))
        self.labelCreationDate_Name_2.setStyleSheet("background:rgb(243, 255, 234);")
        self.labelCreationDate_Name_2.setObjectName("labelCreationDate_Name_2")
        self.gridLayout.addWidget(self.labelCreationDate_Name_2, 1, 0, 1, 1)
        self.labelCreationDate = QtWidgets.QLabel(self.centralwidget)
        self.labelCreationDate.setStyleSheet("background:rgb(243, 255, 234);")
        self.labelCreationDate.setObjectName("labelCreationDate")
        self.gridLayout.addWidget(self.labelCreationDate, 0, 1, 1, 1)
        self.labelCreationDate_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelCreationDate_2.setStyleSheet("background:rgb(243, 255, 234);")
        self.labelCreationDate_2.setObjectName("labelCreationDate_2")
        self.gridLayout.addWidget(self.labelCreationDate_2, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1341, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Введите путь для загрузки   "))
        self.pushButtonDownload.setText(_translate("MainWindow", "Загрузить новую версию   "))
        self.pushButtonBack.setText(_translate("MainWindow", "Назад"))
        self.labelCreationDate_Name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Дата создания</span></p></body></html>"))
        self.labelCreationDate_Name_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Возможность загрузить</span></p></body></html>"))
        self.labelCreationDate.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">123</span></p></body></html>"))
        self.labelCreationDate_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">123</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
