# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AllTP.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ALLTPS(object):
    def setupUi(self, ALLTPS):
        ALLTPS.setObjectName("ALLTPS")
        ALLTPS.resize(723, 597)
        ALLTPS.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(ALLTPS)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 2, 0, 1, 1)
        self.tableWidgetAcrualTP = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetAcrualTP.sizePolicy().hasHeightForWidth())
        self.tableWidgetAcrualTP.setSizePolicy(sizePolicy)
        self.tableWidgetAcrualTP.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetAcrualTP.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetAcrualTP.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetAcrualTP.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetAcrualTP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetAcrualTP.setStyleSheet("background:rgb(243, 255, 234);")
        self.tableWidgetAcrualTP.setObjectName("tableWidgetAcrualTP")
        self.tableWidgetAcrualTP.setColumnCount(1)
        self.tableWidgetAcrualTP.setRowCount(0)
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch) # 1
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(0, item)
        self.gridLayout.addWidget(self.tableWidgetAcrualTP, 1, 0, 1, 1)
        ALLTPS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ALLTPS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 21))
        self.menubar.setObjectName("menubar")
        ALLTPS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ALLTPS)
        self.statusbar.setObjectName("statusbar")
        ALLTPS.setStatusBar(self.statusbar)

        self.retranslateUi(ALLTPS)
        QtCore.QMetaObject.connectSlotsByName(ALLTPS)

    def retranslateUi(self, ALLTPS):
        _translate = QtCore.QCoreApplication.translate
        ALLTPS.setWindowTitle(_translate("ALLTPS", "MainWindow"))
        self.pushButtonBack.setText(_translate("ALLTPS", "Назад"))
        self.tableWidgetAcrualTP.setWhatsThis(_translate("ALLTPS", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(0)
        item.setText(_translate("ALLTPS", "Наименование"))


