# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AllUsers.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllUsers(object):
    def setupUi(self, AllUsers):
        AllUsers.setObjectName("AllUsers")
        AllUsers.resize(800, 600)
        AllUsers.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(AllUsers)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetAcrualTP = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetAcrualTP.sizePolicy().hasHeightForWidth())
        self.tableWidgetAcrualTP.setSizePolicy(sizePolicy)
        self.tableWidgetAcrualTP.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetAcrualTP.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetAcrualTP.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.tableWidgetAcrualTP.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetAcrualTP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetAcrualTP.setStyleSheet("background:rgb(243, 255, 234);")
        self.tableWidgetAcrualTP.setObjectName("tableWidgetAcrualTP")
        self.tableWidgetAcrualTP.setColumnCount(3)
        self.tableWidgetAcrualTP.setRowCount(0)
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.tableWidgetAcrualTP.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAcrualTP.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidgetAcrualTP, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButtotBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtotBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtotBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtotBack.setObjectName("pushButtotBack")
        self.gridLayout.addWidget(self.pushButtotBack, 1, 1, 1, 1)
        AllUsers.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AllUsers)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        AllUsers.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AllUsers)
        self.statusbar.setObjectName("statusbar")
        AllUsers.setStatusBar(self.statusbar)

        self.retranslateUi(AllUsers)
        QtCore.QMetaObject.connectSlotsByName(AllUsers)

    def retranslateUi(self, AllUsers):
        _translate = QtCore.QCoreApplication.translate
        AllUsers.setWindowTitle(_translate("AllUsers", "MainWindow"))
        self.tableWidgetAcrualTP.setWhatsThis(_translate("AllUsers", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(0)
        item.setText(_translate("AllUsers", "Фамилия"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(1)
        item.setText(_translate("AllUsers", "Имя"))
        item = self.tableWidgetAcrualTP.horizontalHeaderItem(2)
        item.setText(_translate("AllUsers", "Отвество"))
        self.pushButton.setText(_translate("AllUsers", "Создать нового пользователя"))
        self.pushButtotBack.setText(_translate("AllUsers", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AllUsers = QtWidgets.QMainWindow()
    ui = Ui_AllUsers()
    ui.setupUi(AllUsers)
    AllUsers.show()
    sys.exit(app.exec_())
