# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArgeementCreateTP.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgreementNewTP(object):
    def setupUi(self, AgreementNewTP):
        AgreementNewTP.setObjectName("AgreementNewTP")
        AgreementNewTP.resize(800, 600)
        AgreementNewTP.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(AgreementNewTP)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonCheckOldAgreement_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckOldAgreement_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCheckOldAgreement_3.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCheckOldAgreement_3.setObjectName("pushButtonCheckOldAgreement_3")
        self.gridLayout.addWidget(self.pushButtonCheckOldAgreement_3, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditPathToDownload = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPathToDownload.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditPathToDownload.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditPathToDownload.setObjectName("lineEditPathToDownload")
        self.gridLayout.addWidget(self.lineEditPathToDownload, 6, 1, 1, 3)
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setMinimumSize(QtCore.QSize(0, 50))
        self.labelName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 0, 1, 1, 3)
        self.labelUserComment = QtWidgets.QLabel(self.centralwidget)
        self.labelUserComment.setMinimumSize(QtCore.QSize(0, 50))
        self.labelUserComment.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelUserComment.setObjectName("labelUserComment")
        self.gridLayout.addWidget(self.labelUserComment, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_2.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 50))
        self.label_6.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 7, 3, 1, 1)
        self.lineEditAdminCommnet = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAdminCommnet.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditAdminCommnet.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditAdminCommnet.setObjectName("lineEditAdminCommnet")
        self.gridLayout.addWidget(self.lineEditAdminCommnet, 5, 1, 1, 3)
        self.pushButtonCheckOldAgreement = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckOldAgreement.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCheckOldAgreement.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCheckOldAgreement.setObjectName("pushButtonCheckOldAgreement")
        self.gridLayout.addWidget(self.pushButtonCheckOldAgreement, 7, 2, 1, 1)
        self.labelCreator = QtWidgets.QLabel(self.centralwidget)
        self.labelCreator.setMinimumSize(QtCore.QSize(0, 50))
        self.labelCreator.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.labelCreator.setObjectName("labelCreator")
        self.gridLayout.addWidget(self.labelCreator, 3, 1, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 50))
        self.label_7.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        self.label_3.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.pushButtonCheckOldAgreement_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckOldAgreement_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonCheckOldAgreement_2.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonCheckOldAgreement_2.setObjectName("pushButtonCheckOldAgreement_2")
        self.gridLayout.addWidget(self.pushButtonCheckOldAgreement_2, 7, 0, 1, 1)
        AgreementNewTP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AgreementNewTP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        AgreementNewTP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AgreementNewTP)
        self.statusbar.setObjectName("statusbar")
        AgreementNewTP.setStatusBar(self.statusbar)

        self.retranslateUi(AgreementNewTP)
        QtCore.QMetaObject.connectSlotsByName(AgreementNewTP)

    def retranslateUi(self, AgreementNewTP):
        _translate = QtCore.QCoreApplication.translate
        AgreementNewTP.setWindowTitle(_translate("AgreementNewTP", "MainWindow"))
        self.pushButtonCheckOldAgreement_3.setText(_translate("AgreementNewTP", "Загрузить"))
        self.label.setText(_translate("AgreementNewTP", "Наименование"))
        self.labelName.setText(_translate("AgreementNewTP", "текст"))
        self.labelUserComment.setText(_translate("AgreementNewTP", "текст"))
        self.label_2.setText(_translate("AgreementNewTP", "Комментарий пользователя"))
        self.label_6.setText(_translate("AgreementNewTP", "Причина отказа"))
        self.pushButtonBack.setText(_translate("AgreementNewTP", "Назад"))
        self.pushButtonCheckOldAgreement.setText(_translate("AgreementNewTP", "Согласовать"))
        self.labelCreator.setText(_translate("AgreementNewTP", "текст"))
        self.label_7.setText(_translate("AgreementNewTP", "Разработчик"))
        self.label_3.setText(_translate("AgreementNewTP", "Путь для выгрузки"))
        self.pushButtonCheckOldAgreement_2.setText(_translate("AgreementNewTP", "Отправить на доработку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgreementNewTP = QtWidgets.QMainWindow()
    ui = Ui_AgreementNewTP()
    ui.setupUi(AgreementNewTP)
    AgreementNewTP.show()
    sys.exit(app.exec_())
