# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangeUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeUser(object):
    def setupUi(self, ChangeUser):
        ChangeUser.setObjectName("ChangeUser")
        ChangeUser.resize(946, 599)
        ChangeUser.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(ChangeUser)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditOtch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditOtch.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditOtch.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditOtch.setObjectName("lineEditOtch")
        self.gridLayout.addWidget(self.lineEditOtch, 2, 1, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditName.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 1, 1, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        self.lineEditFamil = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFamil.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditFamil.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditFamil.setObjectName("lineEditFamil")
        self.gridLayout.addWidget(self.lineEditFamil, 0, 1, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 50))
        self.label_6.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.pushButtonChange = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonChange.setMinimumSize(QtCore.QSize(140, 50))
        self.pushButtonChange.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtonChange.setObjectName("pushButtonChange")
        self.gridLayout.addWidget(self.pushButtonChange, 6, 0, 1, 3)
        self.lineEditLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLogin.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditLogin.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.gridLayout.addWidget(self.lineEditLogin, 3, 1, 1, 4)
        self.scrollAreaAllGrade = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaAllGrade.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollAreaAllGrade.setStyleSheet("background:rgb(243, 255, 234);\n"
"font-size:16pt")
        self.scrollAreaAllGrade.setWidgetResizable(True)
        self.scrollAreaAllGrade.setObjectName("scrollAreaAllGrade")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 608, 298))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollAreaAllGrade.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollAreaAllGrade, 0, 5, 5, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        self.label_3.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditPassword.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 4, 1, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 50))
        self.label_5.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.pushButtotBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtotBack.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtotBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButtotBack.setObjectName("pushButtotBack")
        self.gridLayout.addWidget(self.pushButtotBack, 6, 4, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(140, 50))
        self.pushButton.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 15px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 3, 1, 1)
        ChangeUser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChangeUser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 21))
        self.menubar.setObjectName("menubar")
        ChangeUser.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChangeUser)
        self.statusbar.setObjectName("statusbar")
        ChangeUser.setStatusBar(self.statusbar)

        self.retranslateUi(ChangeUser)
        QtCore.QMetaObject.connectSlotsByName(ChangeUser)

    def retranslateUi(self, ChangeUser):
        _translate = QtCore.QCoreApplication.translate
        ChangeUser.setWindowTitle(_translate("ChangeUser", "MainWindow"))
        self.label.setText(_translate("ChangeUser", "Фамилия"))
        self.label_4.setText(_translate("ChangeUser", "Отчество"))
        self.label_6.setText(_translate("ChangeUser", "Пароль"))
        self.pushButtonChange.setText(_translate("ChangeUser", "Изменить"))
        self.label_3.setText(_translate("ChangeUser", "Имя"))
        self.label_5.setText(_translate("ChangeUser", "Логин"))
        self.pushButtotBack.setText(_translate("ChangeUser", "Назад"))
        self.pushButton.setText(_translate("ChangeUser", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangeUser = QtWidgets.QMainWindow()
    ui = Ui_ChangeUser()
    ui.setupUi(ChangeUser)
    ChangeUser.show()
    sys.exit(app.exec_())
