# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangeGost.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeGost(object):
    def setupUi(self, ChangeGost):
        ChangeGost.setObjectName("ChangeGost")
        ChangeGost.resize(1256, 595)
        ChangeGost.setStyleSheet("background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(83, 160, 81, 255), stop:1 rgba(255, 120, 161, 255))qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 160, 152, 255), stop:1 rgba(248, 255, 198, 255))")
        self.centralwidget = QtWidgets.QWidget(ChangeGost)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Name = QtWidgets.QLabel(self.centralwidget)
        self.label_Name.setMinimumSize(QtCore.QSize(100, 25))
        self.label_Name.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.label_Name.setObjectName("label_Name")
        self.gridLayout.addWidget(self.label_Name, 0, 0, 1, 2)
        self.labelNewFile = QtWidgets.QLabel(self.centralwidget)
        self.labelNewFile.setMinimumSize(QtCore.QSize(300, 50))
        self.labelNewFile.setMaximumSize(QtCore.QSize(150, 16777215))
        self.labelNewFile.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.labelNewFile.setObjectName("labelNewFile")
        self.gridLayout.addWidget(self.labelNewFile, 2, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditName.setMinimumSize(QtCore.QSize(0, 90))
        self.lineEditName.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 0, 2, 1, 5)
        self.labelDownloadPath = QtWidgets.QLabel(self.centralwidget)
        self.labelDownloadPath.setMinimumSize(QtCore.QSize(200, 0))
        self.labelDownloadPath.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.labelDownloadPath.setObjectName("labelDownloadPath")
        self.gridLayout.addWidget(self.labelDownloadPath, 3, 0, 1, 1)
        self.labelPathToFile = QtWidgets.QLabel(self.centralwidget)
        self.labelPathToFile.setMinimumSize(QtCore.QSize(0, 70))
        self.labelPathToFile.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.labelPathToFile.setText("")
        self.labelPathToFile.setObjectName("labelPathToFile")
        self.gridLayout.addWidget(self.labelPathToFile, 2, 1, 1, 6)
        self.lineEditPathDownload = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPathDownload.setMinimumSize(QtCore.QSize(0, 70))
        self.lineEditPathDownload.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.lineEditPathDownload.setObjectName("lineEditPathDownload")
        self.gridLayout.addWidget(self.lineEditPathDownload, 3, 1, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButtonSelectFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSelectFile.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButtonSelectFile.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.pushButtonSelectFile.setObjectName("pushButtonSelectFile")
        self.gridLayout.addWidget(self.pushButtonSelectFile, 4, 0, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButtonBack.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout.addWidget(self.pushButtonBack, 4, 6, 1, 1)
        self.pushButtonDeleteGost = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteGost.setMinimumSize(QtCore.QSize(162, 80))
        self.pushButtonDeleteGost.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.pushButtonDeleteGost.setObjectName("pushButtonDeleteGost")
        self.gridLayout.addWidget(self.pushButtonDeleteGost, 4, 1, 1, 2)
        self.pushButtonAgreement = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAgreement.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButtonAgreement.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.pushButtonAgreement.setObjectName("pushButtonAgreement")
        self.gridLayout.addWidget(self.pushButtonAgreement, 4, 5, 1, 1)
        self.pushButtonDownloadTp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDownloadTp.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButtonDownloadTp.setStyleSheet("background:rgb(243, 255, 234);\n"
"padding: 10;\n"
"font-size: 13pt;")
        self.pushButtonDownloadTp.setObjectName("pushButtonDownloadTp")
        self.gridLayout.addWidget(self.pushButtonDownloadTp, 4, 3, 1, 2)
        ChangeGost.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChangeGost)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1256, 21))
        self.menubar.setObjectName("menubar")
        ChangeGost.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChangeGost)
        self.statusbar.setObjectName("statusbar")
        ChangeGost.setStatusBar(self.statusbar)

        self.retranslateUi(ChangeGost)
        QtCore.QMetaObject.connectSlotsByName(ChangeGost)

    def retranslateUi(self, ChangeGost):
        _translate = QtCore.QCoreApplication.translate
        ChangeGost.setWindowTitle(_translate("ChangeGost", "MainWindow"))
        self.label_Name.setText(_translate("ChangeGost", "<html><head/><body><p><span style=\" font-size:16pt;\">Наименование</span></p></body></html>"))
        self.labelNewFile.setText(_translate("ChangeGost", "<html><head/><body><p><span style=\" font-size:16pt;\">Путь до нового ГОСТ</span></p></body></html>"))
        self.labelDownloadPath.setText(_translate("ChangeGost", "<html><head/><body><p><span style=\" font-size:16pt;\">Путь для загрузки файла</span></p></body></html>"))
        self.pushButtonSelectFile.setText(_translate("ChangeGost", "Выбрать новый Файл"))
        self.pushButtonBack.setText(_translate("ChangeGost", "Назад"))
        self.pushButtonDeleteGost.setText(_translate("ChangeGost", "Удалить"))
        self.pushButtonAgreement.setText(_translate("ChangeGost", "Изменить"))
        self.pushButtonDownloadTp.setText(_translate("ChangeGost", "Загрузить ГОСТ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangeGost = QtWidgets.QMainWindow()
    ui = Ui_ChangeGost()
    ui.setupUi(ChangeGost)
    ChangeGost.show()
    sys.exit(app.exec_())
